Add more spellparts
MinecraftschurliMods/Ars-Magica-Legacy pull request #240
Opened 2022-01-10 14:34 UTC by IchHabeHunger54

Adds all spellparts, except for the following:

- Blizzard
- Falling Star
- Fire Rain
- Mana Blast
- Mana Shield
- Summon

Also has some minor tweaks to some already existing spell parts.

2022-01-11 17:25 UTC, Minecraftschurli requested changes
Just one thing

2022-01-11 17:25 UTC, Minecraftschurli commented on src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/magic/IRiftHelper.java
> +    ItemStackHandler getRift(Player player);
jdoc

2022-01-17 18:38 UTC, pmrkonjic-tgm submitted a review, later dismissed

2022-01-17 19:02 UTC, Minecraftschurli submitted a review, later dismissed

2022-01-20 08:04 UTC, Lprskalo approved these changes

2022-01-20 08:20 UTC, merged