Bosses
MinecraftschurliMods/Ars-Magica-Legacy pull request #269
Opened 2022-03-21 14:49 UTC by pmrkonjic-tgm

2022-03-21 14:59 UTC, Minecraftschurli requested changes
initial review

2022-03-21 14:59 UTC, Minecraftschurli commented on src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/entity/ISpellCasterEntity.java
> +public interface ISpellCasterEntity {
doc

2022-03-21 14:59 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMBlockEntities.java
> +    RegistryObject<BlockEntityType<AltarViewBlockEntity>> ALTAR_VIEW = BLOCK_ENTITIES.register("altar_view",        () -> BlockEntityType.Builder.of(AltarViewBlockEntity::new,        AMBlocks.ALTAR_V
why?

2022-03-21 14:59 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMBlocks.java
> +    RegistryObject<InscriptionTableBlock> INSCRIPTION_TABLE = BLOCKS.register("inscription_table",        InscriptionTableBlock::new);
why?

2022-03-21 15:23 UTC, IchHabeHunger54 commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMBlocks.java
> +    RegistryObject<InscriptionTableBlock> INSCRIPTION_TABLE = BLOCKS.register("inscription_table",        InscriptionTableBlock::new);
intellidumb(TM)

2022-03-21 15:23 UTC, IchHabeHunger54 commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMBlockEntities.java
> +    RegistryObject<BlockEntityType<AltarViewBlockEntity>> ALTAR_VIEW = BLOCK_ENTITIES.register("altar_view",        () -> BlockEntityType.Builder.of(AltarViewBlockEntity::new,        AMBlocks.ALTAR_V
intellidumb(TM)

2022-03-22 07:26 UTC, IchHabeHunger54 submitted a review, later dismissed

2022-03-22 09:09 UTC, Minecraftschurli requested changes
Some things still to do

2022-03-22 09:09 UTC, Minecraftschurli commented on src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/entity/ExecuteSpellGoal.java
> +public class ExecuteSpellGoal<T extends Mob & ISpellCasterEntity> extends Goal {
doc

2022-03-22 09:09 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/entity/EarthGuardian.java
> +        return createMonsterAttributes().add(Attributes.MAX_HEALTH, 120).add(Attributes.ARMOR, 20);
missing mana and burnout attribute

2022-03-22 09:09 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/entity/EnderGuardian.java
> +        return createMonsterAttributes().add(Attributes.MAX_HEALTH, 500).add(Attributes.ARMOR, 20);
missing attributes

2022-03-22 09:09 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/entity/FireGuardian.java
> +        return createMonsterAttributes().add(Attributes.MAX_HEALTH, 250).add(Attributes.ARMOR, 20);
again missing attributes

2022-03-22 09:09 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMEntities.java
> +    RegistryObject<EntityType<Wall>>       WALL       = ENTITIES.register("wall",               () -> EntityType.Builder.of(Wall::new,              MobCategory.MISC)   .clientTrackingRange(8).sized(0
why?

2022-03-22 09:09 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMItems.java
> +    RegistryObject<BlockItem>       OCCULUS      = registerBlockItem64(AMBlocks.OCCULUS);
why?

2022-03-22 11:49 UTC, Minecraftschurli approved these changes
Looks good :shipit:

2022-03-22 11:58 UTC, merged