Explosion component, plus some other spell part things
MinecraftschurliMods/Ars-Magica-Legacy pull request #281
Opened 2022-04-23 15:54 UTC by IchHabeHunger54

2022-04-23 16:01 UTC, Minecraftschurli requested changes
Some little things

2022-04-23 16:01 UTC, Minecraftschurli commented on src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/IPrefabSpellManager.java
> +}
documentation needed

2022-04-23 16:01 UTC, Minecraftschurli commented on src/api/java/com/github/minecraftschurlimods/arsmagicalegacy/api/spell/ISpellTransformationManager.java
> + *
documentation needed

2022-04-23 16:01 UTC, Minecraftschurli commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMSpellParts.java
> -    // TODO contingencies: damage, death, fall, fire, health
leave this in

2022-04-24 11:52 UTC, IchHabeHunger54 commented on src/main/java/com/github/minecraftschurlimods/arsmagicalegacy/common/init/AMSpellParts.java
> -    // TODO contingencies: damage, death, fall, fire, health
Why? It's been added to the project board, should be fine to remove this.

2022-04-28 21:14 UTC, Minecraftschurli approved these changes
Looks good to me (I hope you tested everything client and server) :shipit:

2022-04-28 21:14 UTC, merged